### ISSUE TITLE
Delayed start

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctor-fopub#101]
fopub seems to do nothing for about 13 seconds before starting to process the document (on a reasonably fast and recent computer and using the simple sample.xml document provided). How can I speed it up?

Details:

```
$ git clone git@github.com:asciidoctor/asciidoctor-fopub.git
$ cd asciidoctor-fopub/
$ gedit sample.adoc
```
[copied content provided in the README of this repository]
```
$ asciidoctor -b docbook -d book -a data-uri! sample.adoc
$ ./fopub sample.xml
```
[first run downloads some stuff, takes 29 seconds in total and produces the expected PDF]
```
$ ./fopub sample.xml
```
[second and next runs take 15 seconds in total and produce the expected PDF; for about 13 seconds fopub does not output anything, only then does it start saying “INFOS: Rendered page #1.” and so on]

**Comment by mojavelinux** [comment]
I've been wondering the same thing. Seems like it's trying to resolve something over the network.

**Comment by oliviercailloux** [comment]
Sorry, didn’t understand you. Same thing as what? Do you mean that this delay is a usual behavior?

**Comment by mojavelinux** [comment]
I'm saying I have observed the same problem. I have no idea what is causing it.

**Comment by oliviercailloux** [comment]
Ah ok, I thought it was something specific to my setup, especially given that the README indicates that the application is fast thanks to it working locally. Let me add, in case it is different for you, that for me the delay is systematic: it happens with every document I tried and at each run.

**Comment by mojavelinux** [comment]
I can confirm it is happening on every document for me too. It didn't used
to do this, so something changed recently.

**Comment by mojavelinux** [comment]
This issue is outside of our control and no one knows how to fix it. Closing.
