### ISSUE TITLE
Bash script is unable to run because of the gradle setup

### ISSUE THREAD

**Issue by lemosbash** [asciidoctor/asciidoctor-fopub#102]
The bash script included in this repository, mentioned on the **README.adoc** have problems with it's gradle setup, it fetches what it needs, but dies in gradle exception, with no further stacktrace.

Using the example text that is on the README (and producing a docbook with the asciidoctor code snippet right bellow), the build starts, fetches gradle, but dies on a exception, with no further information, only a wikipage for gradle, that seens not much helpful to deal with this problem. With `asciidoctor-fopub/fopub example.xml --stacktrace`, the following is printed to the stdout:

_https://pastebin.com/iCXrAvPt_

This test is running under a ubuntu temporary container, ran with `podman run --rm -it ubuntu bash`, installing only the necessary tools to run this tool. Basic information for the environment:

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
Shell: bash 5.0.17
Kernel: 5.15.41-gentoo

**Comment by mojavelinux** [comment]
This project is no longer being actively maintained. If you'd like to propose a fix for this problem, I will review and merge it.

**Comment by dullahan2084** [comment]
In case it helps, changing the version of gradle (changed 'gradle-4.9-bin.zip' to 'gradle-4.10-bin.zip' in 'gradle/wrapper/gradle-wrapper.properties') solved the issue for me.

**Comment by mojavelinux** [comment]
If you'd like to make a PR with this change, I'll see that it gets merged.
