### ISSUE TITLE
Add custom docbook-xsl directory option to fopdf.bat

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-fopub#17]
Add the custom docbook-xsl directory option to fopdf.bat to align with #13.

**Comment by stallio** [comment]
Is there some other way to use custom XSL in Windows, or is the only way to edit the contents of the docbook-xsl folder?

**Comment by mojavelinux** [comment]
Not really. This issue needs to be resolved. Otherwise, the information is not passed to the processor and it won't know to use another directory.

In addition to the commandline option, we could also consider adding an environment variable for the location of the dockbook-xsl folder.

Of course, you can always feel free to hack the contents of the docbook-xsl folder yourself. However, you'd need to manage those changes so that they don't get overridden accidentally if you update fopub. It's not the recommended way, but it is a way.

**Comment by apnadkarni** [comment]
One simple change is to change the following line in fopub.bat
`set DOCBOOK_XSL_DIR=%FOPUB_DIR%\docbook-xsl`
to
`if not defined DOCBOOK_XSL_DIR set DOCBOOK_XSL_DIR=%FOPUB_DIR%\docbook-xsl`
Then define DOCBOOK_XSL_DIR in the environment before invoking fopub

**Comment by mojavelinux** [comment]
:+1: Would you like to propose that change?

**Comment by apnadkarni** [comment]
Sure but first I'll try to make the fopub.bat closer to fopub in functionality. Though this Windows batch file language is giving me a headache...

**Comment by apnadkarni** [comment]
OK, I've submitted a pull request with the changes. fopub.bat should now have the same interface as the Unix version.

**Comment by mojavelinux** [comment]
Awesome! Thank you! I'll review asap.
