### ISSUE TITLE
paragraph heading is not followed by newline

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-fopub#41]
No newline between "header" and "lorem".

```asciidoc
= Test

.Paragraph header
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod 
tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim 
veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea 
commodo consequat. Duis aute irure dolor inreprehenderit in voluptate 
velit esse cillum dolore eu fugiat nullapariatur. 
```

**Comment by getreu** [comment]
Any progress on this? We still need the fopub backend for production use (i.e. footnotes etc.)!

I tested `asciidoctor-pdf` and `asciidoctor` html, both render paragraph titles right.
Also the xml seems ok to me. 

## adoc2xml
![adoc2xml](https://cloud.githubusercontent.com/assets/579082/10870240/79892f88-80ce-11e5-8567-f742fc0b74e6.png)

## adoc2docbook2fopub
![adoc2docbook2fopub](https://cloud.githubusercontent.com/assets/579082/10870195/8f648c2c-80cd-11e5-95e9-0a8aa4e0feb7.png)

## adoc2asciidoctor-pdf
![adoc2asciidoctor-pdf](https://cloud.githubusercontent.com/assets/579082/10870196/935659aa-80cd-11e5-9c9d-c28e23deac22.png)

## adoc2html
![adoc2html](https://cloud.githubusercontent.com/assets/579082/10870198/9734947e-80cd-11e5-992d-95177e2e56ef.png)

**Comment by mojavelinux** [comment]
This behavior can be changed by modifying the template for `db:formalpara/db:title | formalpara/title`. I've proposed a fix in PR #51.

Keep in mind this isn't always the desired behavior, so it might be good to add a parameter to control this option.

**Comment by mojavelinux** [comment]
I've added the XSL parameter `runinhead.default.title.break.after` to control the behavior. By default it will add a newline, but this can be reverted.

```
./fopub sample.xml -param runinhead.default.title.break.after 0
```

**Comment by mojavelinux** [comment]
I also fixed the layout when the break is disabled so that the title and the content aren't mashed up next to one another.

**Comment by mojavelinux** [comment]
Recall that the punctuation character at the end of the title can also be controlled, for when you disable the newline:

```
./fopub sample.xml -param runinhead.default.title.break.after 0 \
  -param runinhead.default.title.end.punct .
```

**Comment by getreu** [comment]
I tested you patch. I works fine and looks really cool! Thank you!
