### ISSUE TITLE
Glossary missing glossary tags

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor-fopub#45]
Hi Guys,

Following the example in the readme, using my own .adoc and the glossary coughs up an error when creating PDF because the `glossentry` tags are not wrapped in a `glossary` tag in the docbook.

Adding a glossary to the sample

````
[glossary]
TEST::
        This.
````

reproduces the issue for me when using 

````
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]) (lc:US-ASCII fs:US-ASCII in:- ex:US-ASCII)
````
Wrapping the `glossentry` tags manually in a `glossary` tags fixes the pdf generation.

**Comment by mojavelinux** [comment]
Technically this is because the glossary style must also be on the section.

```
[glossary]
== Glossary

[glossary]
TEST::
  This.
```

This is an historical requirement of AsciiDoc. We could rethink the policy in Asciidoctor if this is too restrictive.

**Comment by plaindocs** [comment]
Aah right - I missed that - info is a bit thin on the ground.

http://asciidoctor.org/docs/user-manual/#user-glossary is empty, and the code section above it also looks a bit off:

````
[glossary]
== Part 1 Glossary

mud:: wet, cold dirt
````

Shall I make a PR for that section?

**Comment by mojavelinux** [comment]
Please do.

Currently the only place this information exists is in the "old" manual. In fact, it's only a very brief note. We can do better in the Asciidoctor user manual.

> To generate valid DocBook output glossary lists must be located in a section that uses the glossary section markup template.

**Comment by plaindocs** [comment]
Done. https://github.com/asciidoctor/asciidoctor.org/pull/346

**Comment by mojavelinux** [comment]
Thank you so much for contributing this documentation enhancement! :beers:
