### ISSUE TITLE
sed error when executing fopub

### ISSUE THREAD

**Issue by neontapir** [asciidoctor/asciidoctor-fopub#46]
On my MacbookPro, I run `asciidoctor -b docbook -d book -a data-uri! giants.adoc` to produce a DocBook XML file called `giants.xml`. However, when I try to process that file with `fopub giants.xml` from the folder containing my document, I get the following error:

    sed: 1: "giants.xml": extra characters at the end of g command
    Warning: Could not get charToByteConverterClass!
    Jul 02, 2015 10:20:59 AM org.apache.fop.events.LoggingEventListener processEvent
    INFO: Rendered page #1.

Except for a couple of font warnings, the rest of the document processes successfully. However, a PDF file is generated, though I would expect an EPUB book.

**Comment by mojavelinux** [comment]
The only use of sed in the script is on the following line:

https://github.com/asciidoctor/asciidoctor-fopub/blob/master/fopub#L109

Something is going wrong there. You could just comment it out.

> a PDF file is generated, though I would expect an EPUB book.

fopub only does PDF at this point. The script would need to be enhanced to accept a format option (like a2x) that is passed to the processor so it uses the appropriate XSLT files.

**Comment by neontapir** [comment]
Thanks, commenting it out solved my issue.
