### ISSUE TITLE
How to change the font size of java code

### ISSUE THREAD

**Issue by MarcoIeni** [asciidoctor/asciidoctor-fopub#52]
Sorry about this issue, maybe it is a stupid question, but I didn't found anything on the internet about that.

In addition, there is a way to change the size of an external file? Something like

```
include::myfile.java[fontsize=3]
```

**Comment by mojavelinux** [comment]
There's no way to control this from AsciiDoc. You have to modify the XSL templates or pass an XSL param. See https://github.com/asciidoctor/asciidoctor-fopub/blob/master/src/dist/docbook-xsl/fo-pdf.xsl#L178-L189.

**Comment by MarcoIeni** [comment]
solved editing that file, thank you very much!

**Comment by mojavelinux** [comment]
:+1:
