### ISSUE TITLE
Adding libraries to FOP

### ISSUE THREAD

**Issue by Thoragan** [asciidoctor/asciidoctor-fopub#58]
Hi!
I want to add hyphenation pattern for Russian to my project.
So I downloaded `fop-hyph.jar` from http://offo.sourceforge.net
After that I tried to include it to classpath, but there is no effect.

In file 'asciidoctor-fopub/build/fopub/bin/fopub' classpath variable is overwriting by command:
`CLASSPATH=$APP_HOME/lib/fopub-1.0.0-SNAPSHOT.jar:..` (line 63).

After changing it to: `CLASSPATH=$CLASSPATH:$APP_HOME/lib/fopub-1.0.0-SNAPSHOT.jar:..` and including `fop-hyph.jar` into classpath in my makefile hyphenation starts working.

Please, fix it, or give me advise how to solve this issue in shorter way.

Best regards.

**Comment by mojavelinux** [comment]
I added the library to build.gradle with instructions about how to enable it.

See https://github.com/asciidoctor/asciidoctor-fopub/blob/c49ad01c0169e1b73d4c3d6dfcec6f4f22ba3ad6/build.gradle#L24-L25

We may want to document how to add libraries to FOP, in general, in the README.
