### ISSUE TITLE
How to enable Russian Cyrillic letters in MathML?

### ISSUE THREAD

**Issue by Thoragan** [asciidoctor/asciidoctor-fopub#59]
I want to use Russian Cyrillic letters in [asciimath] blocks. How can I enable rendering it asciidoctor-fopub? All I found was this: http://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-ive2.html

**Comment by mojavelinux** [comment]
Could you provide an example of the formula you are trying to use?

What I recommend is just entering the Unicode glyph directly.

```
:stem: asciimath

[stem]
++++
text(Память: )M_(доп)(n) = Theta(N)
++++
```

Then run:

```
asciidoctor -b docbook document.adoc
```

I have noticed, however, that this causes asciimath to choke. You should raise that issue in https://github.com/pepijnve/asciimath.

**Comment by Thoragan** [comment]
This issue resolved in asciimath

https://github.com/pepijnve/asciimath/issues/2

**Comment by mojavelinux** [comment]
:+1:
