### ISSUE TITLE
Syntax highlighting for Rust added

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-fopub#66]
I added syntax highlighting for Rust. I wanted to submit a separate pull request, but it somehow it got merged into my previous pull request #62 . Sorry. 
Jens

**Comment by getreu** [comment]
highlighting definitions updated from upstream and new languages added

**Comment by mojavelinux** [comment]
This was resolved by a9c62a7f88256c0eaa530e765e943b28f7e3e68f.
