### ISSUE TITLE
Error message: WARNING: Invalid property value encountered in border=""

### ISSUE THREAD

**Issue by apnadkarni** [asciidoctor/asciidoctor-fopub#80]
The error message in the subject shows up because of the following fragment (starting at line 105) in src/dist/docbook-xsl/common.xsl

<xsl:attribute-set name="shade.verbatim.style">
    <xsl:attribute name="border">0</xsl:attribute>
    <xsl:attribute name="background-color">#E0E0E0</xsl:attribute>
</xsl:attribute-set>

Changing the border attribute to "none" instead of "0" causes the message to go away but I am not sure what was intended. There is no change in my output in any case.

/Ashok

**Comment by mojavelinux** [comment]
I don't really know what the intention was either. You are correct that the value should be none.
