### ISSUE TITLE
Call for maintainer(s)

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-fopub#89]
I'm looking for a maintainer for this project. My focus is elsewhere right now, but I know many people still rely on the DocBook toolchain. I'd like to see this project continue to evolve under different leadership.

If you're considering becoming the maintainer of this project, know that you'd have the freedom to take a different approach to integrating the DocBook / Apache FO toolchain other than Gradle. Using Gradle is not a hard requirement. The only requirement is to fill the original mission of the project, which is to provide a way to to run the DocBook toolchain without having to rely on a local install. In short, it's a more portable and modern version of a2x from AsciiDoc Py.

**Comment by getreu** [comment]
Maybe @bsmith-n4 is interested? [Commits · NumberFour/asciidoctor-fopub](https://github.com/NumberFour/asciidoctor-fopub/commits?author=bsmith-n4)

**Comment by mojavelinux** [comment]
As no one has come forward, I'm archiving this repository. If you would like to see it continue, please join the project chat at https://chat.asciidoctor.org and make your intentions known.
