### ISSUE TITLE
An italic phrase enclosed in bold formatting does not appear as bold italic

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-fopub#90]
As reported in https://github.com/asciidoctor/asciidoctor/issues/1698, if an italic phrase is enclosed in bold formatting, the text in the PDF only appears in bold, not bold italic.

Example:

```
*_bold italic phrase_*
```

Observed:

![actual](https://user-images.githubusercontent.com/79351/46986756-3a8ce800-d0ae-11e8-9f02-c7ce0786ecaf.png)

Expected:

![expected](https://user-images.githubusercontent.com/79351/46986764-3eb90580-d0ae-11e8-93d7-79da9467eedc.png)

**Comment by andrewcarver** [comment]
Thanks, Dan!!!

**Comment by mojavelinux** [comment]
You're welcome. Thanks for reporting. That one was a tough one to notice!

**Comment by andrewcarver** [comment]
Well, I wasn't the one who noticed it; but I did notice that you had completed, quickly, a self-appointed task that was likely not your favorite sort--yet, had received no thanks--which is, I suspect, far too typical of your work for us. (Though, I'm not sure how we could possibly thank you enough, anyway, for all you have done and do for AsciiDoc.) So, I thought I should make the task just a LITTLE less thankless :-/

**Comment by mojavelinux** [comment]
Well, it was very welcomed indeed! :sun_with_face:
