### ISSUE TITLE
Feature request: add a switch to generate html

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-fopub#92]
As the layout description is generic, it should no be too difficult to render something nice into html.

This would be very useful for people like me, who use `asciidoctor-fopub` in their docbook5 toolchain.

**Comment by mojavelinux** [comment]
This is really just a matter of expanding on the case statement for $FORMAT. Any format the DocBook toolchain supports should work here, in theory.

https://github.com/asciidoctor/asciidoctor-fopub/blob/master/fopub#L122-L135

**Comment by getreu** [comment]
I looked up the [Apache FOP Output Formats](https://xmlgraphics.apache.org/fop/0.95/output.html#wishlist). Unfortunately there is no html renderer. I tried the `rtf` render and then converted `.rtf` to `.hml` with libreoffice. The result is not perfect but kind of usable. Anyway, this hack is not recommended for production.
As there is no chance to get this done with `fop` I close this issue.

**Comment by mojavelinux** [comment]
That's not correct. FOP is only being used here to make PDF. If you want to make another format, you just have to instruct the toolchain to use the appropriate stylesheets (in which case it case it does not go through FOP). One of the backends that the DocBook toolchain supports is xhtml. So just set that as the target format and it will work. (This is exactly the same as a2x).

**Comment by mojavelinux** [comment]
Oops, my mistake. I had forgotten we are using fop to run the stylesheets. In that case, you are correct. Since fopub is using fop to run the stylesheets, xhtml comes off the table.

**Comment by mojavelinux** [comment]
The toolchain is almost set up to be able to make use of the XSL for xhtml output, but not quite. Some modifications would have to be made. In this sense, fopub is not a replacement for a2x.

**Comment by mojavelinux** [comment]
I've submitted a PR to get you going. It probably needs some refinement.

See https://github.com/asciidoctor/asciidoctor-fopub/pull/93

**Comment by getreu** [comment]
I tested you PR and it works nicely. Thank you!
For me this is a read added value, because I do not have to maintain 2 different toolchains any more.

**Comment by getreu** [comment]
Although we have a working implementation now, I suggest to leave this issue open:
We still could add some css styling later to obtain a similar and as beautiful layout as in the .pdf rendition.

**Comment by mojavelinux** [comment]
I've given you access to this repository. If you accept, you can merge at will.

**Comment by mojavelinux** [comment]
> I suggest to leave this issue open

To help keep a project moving, the strategy I recommend is to aggressively close issues and reopen new ones to handle follow-up tasks. If you leave issues open, they tend to just die on the vine. But new issues get a fresh outlook and often have more luck at getting resolved. The cycle of issue life.

**Comment by getreu** [comment]
You are right. I agree.
